name: ARP Scanner Linux
on: [push,pull_request]
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        platform: [x32, x64]
        compiler: [gcc]
        include:
        - os: ubuntu-latest
          platform: x64
          compiler: gcc
        - os: ubuntu-latest
          platform: x32
          compiler: gcc

    name: ARP Scanner Linux ${{matrix.compiler}} ${{matrix.platform}}
    steps:
    - uses: actions/checkout@v1
    
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake

      shell: bash
      working-directory: ${{runner.workspace}}/build

      env:
        CC: ${{ matrix.compiler }}
      run: |
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE 

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE